version: 2.1

orbs:
  node: circleci/node@5.0.2

parameters:
  workflow:
    type: string
    default: ""

jobs:
  run-ci-backend-tests:
    executor:
      name: node/default 
    resource_class: small
    steps:
      - checkout
      
workflows:
  test-ci-backend:
    jobs:
      - run-ci-backend-tests