version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  run-ci-backend-tests:
    executor:
      name: node/default 
    resource_class: small
    steps:
      - checkout
      - run:
          command: |
           echo "i'm scheduled"
      
workflows:
  test-ci-backend:
    jobs:
      - run-ci-backend-tests