version: 2.1

orbs: 
  slack: circleci/slack@4.5.1

jobs:
  test-install-py:
    docker:
      - image: "cimg/android:2021.10.2"
    resource_class: small
    steps:
      - checkout
      - run: 
          command: |
            sudo apt update
            sudo apt install -y python3
            python3.8 --version
      - slack/notify:
          event: pass
          template: basic_success_1
            
workflows:
  py-workflow:
    jobs:
      - test-install-py:
          context:
            - slack-orb